name: project-group25
dependencies:
  - python=3.10
  - sklearn=1.2
  - jupyterlab=3.6
  - numpy=1.23
  - pandas=1.5
  - matplotlib=3.6
  - statsmodels=0.13
  - seaborn=0.12
  - xarray
  - decorator=5.1
  - ipykernel
  